name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set ownership
      run: |
        # this is to fix GIT not liking owner of the checkout dir
        chown -R $(id -u):$(id -g) $PWD

    - name: Generate PDF files
      run: make

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore(build): auto-generate pdf files"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        add_options: '-A'
